<?php

// Include DatabaseHelper.php file
require_once('DocumentsDatabaseHelper.php');

// Instantiate DatabaseHelper class
$database = new DocumentsDatabaseHelper();

$guid='';
if (isset($_GET['guid'])) {
    $guid = $_GET['guid'];
}

$a6z='';
if (isset($_GET['a6z'])) {
    $a6z = $_GET['a6z'];
}

$document_url='';
if (isset($_GET['document_url'])) {
    $document_url = $_GET['document_url'];
}

//Fetch data from database
$document_array = $database->selectAllDocuments($guid, $a6z, $document_url);
?>

<html>
<head>
    <title>Documents</title>
    <link rel="stylesheet" href="../static/styles/menu-bar.css"/>
</head>

<body style="margin-top: 0px">
<ul id="menu-bar">
    <li><a href="../index.php">Home</a></li>
    <li><a class="active" href="../documents/doc_crud.php">Documents</a></li>
    <li><a href="../employees/emp_crud.php">Employees</a></li>
    <li><a href="../types/typ_crud.php">Types</a></li>
</ul>
<h1>Documents</h1>

<!-- Add Person -->
<h2>Add Document: </h2>
<form method="post" action="doc_add.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <!-- Name textbox -->
    <div>
        <label for="new_name">A6Z:</label>
        <input id="new_name" name="a6z" type="text" maxlength="20">
    </div>
    <br>

    <!-- Surname textbox -->
    <div>
        <label for="new_surname">Document URL:</label>
        <input id="new_surname" name="document_url" type="text" maxlength="20">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Add Document
        </button>
    </div>
</form>
<br>
<hr>

<!-- Delete Person -->
<h2>Delete Document: </h2>
<form method="post" action="doc_delete.php">
    <!-- ID textbox -->
    <div>
        <label for="doc_guid">ID:</label>
        <input id="doc_guid" name="id" type="number" min="0">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Delete Document
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search form -->
<h2>Documents Search:</h2>
<form method="get">
    <!-- GUID textbox:-->
    <div>
        <label for="guid_inp">GUID:</label>
        <input id="guid_inp" name="guid" type="number" value='<?php echo $guid; ?>' min="0">
    </div>
    <br>

    <!-- a6z textbox:-->
    <div>
        <label for="a6z_inp">A6Z:</label>
        <input id="_inp" name="a6z" type="text" class="form-control input-md" value='<?php echo $a6z; ?>'
               maxlength="12">
    </div>
    <br>

    <!-- Surname textbox:-->
    <div>
        <label for="document_url_inp">Document URL:</label>
        <input id="document_url_inp" name="document_url" type="text"
               value='<?php echo $document_url; ?>' maxlength="40">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button id='submit' type='submit'>
            Search
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search result -->
<h2>Documents Search Result:</h2>
<table>
    <tr>
        <th>GUID</th>
        <th>A6Z</th>
        <th>Document URL</th>
    </tr>
    <?php foreach ($document_array as $document) : ?>
        <tr>
            <td><?php echo $document['GUID']; ?>  </td>
            <td><?php echo $document['A6Z']; ?>  </td>
            <td><?php echo $document['DOCUMENT_URL']; ?>  </td>
        </tr>
    <?php endforeach; ?>
</table>

</body>
</html>