drop procedure p_delete_type;
drop procedure p_delete_employee;
drop procedure p_delete_document;
drop table affects;
drop table isFiled;
drop table incidents;
drop table Employees;
drop table incidentReports;
drop table components;
drop table types;
drop trigger documents_guid_trg;
drop sequence document_seq;
drop table documents;
commit;
