<?php

// Include DatabaseHelper.php file
require_once('../DatabaseHelpers/ComponentsDatabaseHelper.php');
$database = new ComponentsDatabaseHelper();
require_once('../DatabaseHelpers/TypesDatabaseHelper.php');
$typ_database = new TypesDatabaseHelper();

$snr='';
if (isset($_GET['snr'])) {
    $snr = $_GET['snr'];
}

$pnr='';
if (isset($_GET['pnr'])) {
    $pnr = $_GET['pnr'];
}

$tid='';
if (isset($_GET['tid'])) {
    $tid = $_GET['tid'];
}

$shipping='';
if (isset($_GET['shipping'])&&$_GET['shipping']!=''){
    $shipping = date("d-M-y", strtotime($_GET['shipping']));
}

$installation='';
if (isset($_GET['installation'])&&$_GET['installation']!='') {
    $installation = date("d-M-y", strtotime($_GET['installation']));
}

$kv2='';
if (isset($_GET['kv2'])) {
    $kv2 = $_GET['kv2'];
}

if($snr!=''||$pnr!=''||$tid!=''||$shipping!=''||$installation!=''||$kv2!=''){
    $component_array = $database->selectAllComponents($snr, $pnr,$tid,$kv2, $shipping, $installation,50);
    $component_count = $database->countAllComponents($snr, $pnr,$tid, $kv2, $shipping, $installation);
}

$component_array_full = $database->selectAllComponents($snr, $pnr,$tid,$kv2, $shipping, $installation,'');
$type_array_full = $typ_database->selectAllTypes('', '','', '', '','','');
?>

<html>
<head>
    <title>Components</title>
    <link rel="stylesheet" href="../static/styles/menu-bar.css"/>
    <link rel="stylesheet" href="../static/styles/forms.css"/>
</head>

<body style="margin-top: 0px;padding-left: 10px;padding-right: 10px;">
<ul id="menu-bar">
    <li><a href="../index.php">Home</a></li>
    <li><a href="../documents/doc_crud.php">Documents</a></li>
    <li><a href="../employees/emp_crud.php">Employees</a></li>
    <li><a href="../types/typ_crud.php">Types</a></li>
    <li><a class="active" href="../components/comp_crud.php">Components</a></li>
    <li><a href="../incidents/inc_crud.php">Incidents</a></li>
</ul>
<h1>Types</h1>

<!-- Add Person -->
<h2>Add Component: </h2>
<form method="post" action="comp_add.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <!-- Name textbox -->
    <div>
        <label for="new_parent" class="label">Parent Nr:</label>
        <input id="new_parent" name="parent_nr" list="parent">
        <datalist id="parent">
            <?php foreach ($component_array_full as $component) : ?>
                <option value=<?php echo $component['SERIAL_NR']; ?>><?php echo $component['SERIAL_NR']; ?></option>
            <?php endforeach; ?>
        </datalist>
    </div>
    <div>
        <label for="new_type" class="label">Type ID:</label>
        <input id="new_type" name="tid" list="kv2">
        <datalist id="kv2">
            <?php foreach ($type_array_full as $type) : ?>
                <option value=<?php echo $type['GUID']; ?>><?php echo $type['KV2']; ?></option>
            <?php endforeach; ?>
        </datalist>
    </div>
    <div>
        <label for="new_shipping" class="label">Shipping Date:</label>
        <input id="new_shipping" name="shipping" type="date">
    </div>
    <div>
        <label for="new_installation" class="label">Installation Date:</label>
        <input id="new_installation" name="installation" type="date"'>
    </div>
    <div>
        <button type="submit" class="button-submit">
            Add
        </button>
    </div>
</form>
<br>
<hr>

<!-- Delete Person -->
<h2>Delete Component: </h2>
<form method="post" action="comp_delete.php">
    <!-- ID textbox -->
    <div>
        <label for="comp_snr" class="label">Serial Nr:</label>
        <input id="comp_snr" name="snr" type="number" min="0">
    </div>
    <div>
        <button type="submit" class="button-submit">
            Delete
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search form -->
<h2>Component Search:</h2>
<form method="get">
    <!-- $snr, $pnr,$tid,$kv2, $shipping, $installation-->
    <div>
        <label for="snr_inp" class="label">Serial Nr:</label>
        <input id="snr_inp" name="snr" type="number" value='<?php echo $snr; ?>' min="0">
    </div>
    <div>
        <label for="pnr_inp" class="label">Parent Nr:</label>
        <input id="pnr_inp" name="pnr" type="number" value='<?php echo $pnr; ?>' min="0">
    </div>
    <div>
        <label for="kv2_inp" class="label">AZ6:</label>
        <input id="kv2_inp" name="kv2" type="text"
               value='<?php echo $kv2; ?>' maxlength="12">
    </div>
    <div>
        <label for="shipping_inp" class="label">Specification ID:</label>
        <input id="shipping_inp" name="shipping" type="date" value='<?php echo $shipping; ?>'>
    </div>
    <div>
        <label for="installation_inp" class="label">Specification ID:</label>
        <input id="installation_inp" name="installation" type="date" value='<?php echo $shipping; ?>'>
    </div>
    <div>
        <button id='submit' type='submit' class="button-submit">
            Search
        </button>
    </div>
</form>
<br>
<hr>

<?php if($snr!=''||$pnr!=''||$tid!=''||$kv2!=''|| $shipping!=''|| $installation!=''){?>
<!-- Search result -->
<h2>Components Search Result:</h2>
<h3>(Found <?php echo $component_count[0]; ?>, showing <?php echo min($component_count[0], 50); ?>) </h3>
<table>
    <tr>
        <th>Serial Nr.</th>
        <th>Parent Nr.</th>
        <th>KV2</th>
        <th>Shipping Date</th>
        <th>Installation Date</th>
        <th>Delete</th>
    </tr>
    <?php foreach ($component_array as $component) : ?>
        <tr>
            <td><?php echo $component['SERIAL_NR']; ?>  </td>
            <td><?php echo $component['PARENT_NR']; ?>  </td>
            <td><?php echo $component['KV2']; ?>  </td>
            <td><?php echo $component['SHIPPING_DATE']; ?>  </td>
            <td><?php echo $component['INSTALLATION_DATE']; ?>  </td>
            <td>
                <form method="post" action="comp_delete.php">
                    <input name="snr" type="hidden" value="<?php echo $component['SERIAL_NR']; ?>">
                    <button id="button-list" type="submit" <?php if ($database->countChildren($component['SERIAL_NR'])[0] != 0){ ?> disabled <?php } ?>>
                        <img src="../static/imgs/trashcan.png" alt="Del" width="20">
                    </button>
                </form>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php }else{?>
    <h2>Components Tree Structure:</h2>
<?php
    function treeStructure($database, $pnr,$layer){
        $colors=array("#bbbbbb","#a1a1a1");
        $nextLayer=$layer+1;
        $component_array = $database->selectAllComponentsByParent($pnr);
        if(count($component_array)>0){
        echo "<div style='padding: 5px;margin: 5px;border: solid black 1px;border-radius: 5px;background-color: {$colors[$layer%2]}'>";
        foreach ($component_array as $component){
            echo "<div style=''>Serial Nr: {$component['SERIAL_NR']}<br>KV2: {$component['KV2']} </div>";
                if ($database->countChildren($component['SERIAL_NR'])[0] == 0){
                    echo "
                    <form method='post' action='comp_delete.php'>
                        <input name='snr' type='hidden' value='{$component['SERIAL_NR']}'>
                        <button id='button-list' type='submit'>
                            <img src='../static/imgs/trashcan.png' alt='Del' width='20'>
                        </button>
                    </form>";
                }
            if($nextLayer<7)
                treeStructure($database,$component['SERIAL_NR'],$nextLayer);
        }
        echo "</div>";
        }
    }

    treeStructure($database,'null',0);
}?>
</body>
</html>