<?php

// Include DatabaseHelper.php file
require_once('../DatabaseHelpers/TypesDatabaseHelper.php');
$database = new TypesDatabaseHelper();
require_once('../DatabaseHelpers/DocumentsDatabaseHelper.php');
$doc_database = new DocumentsDatabaseHelper();

$guid='';
if (isset($_GET['guid'])) {
    $guid = $_GET['guid'];
}

$spec_id='';
if (isset($_GET['spec_id'])) {
    $spec_id = $_GET['spec_id'];
}

$az6='';
if (isset($_GET['az6'])) {
    $az6 = $_GET['az6'];
}

$kv2='';
if (isset($_GET['kv2'])) {
    $kv2 = $_GET['kv2'];
}

$supplier='';
if (isset($_GET['supplier'])) {
    $supplier = $_GET['supplier'];
}

$type_cost='';
if (isset($_GET['type_cost'])) {
    $type_cost = $_GET['type_cost'];
}
//Fetch data from database
$type_array = $database->selectAllTypes($guid, $spec_id,$az6, $kv2, $supplier, $type_cost);
$doc_array = $doc_database->selectUnusedSpec();
?>

<html>
<head>
    <title>Types</title>
    <link rel="stylesheet" href="../static/styles/menu-bar.css"/>
</head>

<body style="margin-top: 0px">
<ul id="menu-bar">
    <li><a href="../index.php">Home</a></li>
    <li><a href="../documents/doc_crud.php">Documents</a></li>
    <li><a href="../types/emp_crud.php">Employees</a></li>
    <li><a class="active" href="../types/typ_crud.php">Types</a></li>
</ul>
<h1>Types</h1>

<!-- Add Person -->
<h2>Add Type: </h2>
<form method="post" action="type_add.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <!-- Name textbox -->
    <div>
        <label for="new_spec">Specification ID:</label>
        <input id="new_spec" name="spec_id" list="az6">
        <datalist id="az6">
            <?php foreach ($doc_array as $document) : ?>
                <option value=<?php echo $document['GUID']; ?>><?php echo $document['AZ6']; ?></option>
            <?php endforeach; ?>
        </datalist>
    </div>
    <br>
    <div>
        <label for="new_kv2">KV2:</label>
        <input id="new_kv2" name="kv2" type="text" maxlength="12">
    </div>
    <br>
    <div>
        <label for="new_supplier">Supplier:</label>
        <input id="new_supplier" name="supplier" type="text" maxlength="60">
    </div>
    <br>
    <div>
        <label for="new_cost">Cost:</label>
        <input id="new_cost" name="cost" type="number" min="0">
    </div>
    <br>
    <div>
        <button type="submit">
            Add Type
        </button>
    </div>
</form>
<br>
<hr>

<!-- Delete Person -->
<h2>Delete Type: </h2>
<form method="post" action="emp_delete.php">
    <!-- ID textbox -->
    <div>
        <label for="emp_guid">ID:</label>
        <input id="emp_guid" name="empid" type="number" min="0">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Delete Tyoe
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search form -->
<h2>Tyoes Search:</h2>
<form method="get">
    <!-- GUID textbox:-->
    <div>
        <label for="guid_inp">ID:</label>
        <input id="guid_inp" name="guid" type="number" value='<?php echo $guid; ?>' min="0">
    </div>
    <br>

    <div>
        <label for="spec_inp">Specification ID:</label>
        <input id="spec_inp" name="spec" type="number" value='<?php echo $guid; ?>' min="0">
    </div>
    <br>
    <div>
        <label for="az6_inp">AZ6:</label>
        <input id="az6_inp" name="az6" type="text"
               value='<?php echo $az6; ?>' maxlength="12">
    </div>
    <br>
    <!-- Surname textbox:-->
    <div>
        <label for="kv2_inp">KV2:</label>
        <input id="kv2_inp" name="kv2" type="text"
               value='<?php echo $kv2; ?>' maxlength="12">
    </div>
    <br>
    <div>
        <label for="supplier_inp">Supplier:</label>
        <input id="supplier_inp" name="supplier" type="text"
               value='<?php echo $supplier; ?>' maxlength="60">
    </div>
    <br>
    <div>
        <label for="cost_inp">Cost:</label>
        <input id="cost_inp" name="cost" type="number"
               value='<?php echo $type_cost; ?>' min="0">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button id='submit' type='submit'>
            Search
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search result -->
<h2>Types Search Result:</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Specification ID</th>
        <th>AZ6</th>
        <th>KV2</th>
        <th>Supplier</th>
        <th>Cost</th>
    </tr>
    <?php foreach ($type_array as $type) : ?>
        <tr>
            <td><?php echo $type['GUID']; ?>  </td>
            <td><?php echo $type['SPECIFICATION_ID']; ?>  </td>
            <td><?php echo $type['AZ6']; ?>  </td>
            <td><?php echo $type['KV2']; ?>  </td>
            <td><?php echo $type['SUPPLIER']; ?>  </td>
            <td><?php echo $type['TYPE_COST']; ?>  </td>
        </tr>
    <?php endforeach; ?>
</table>

</body>
</html>